# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\pyqt\ui\alt_val_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog2(object):
    def setupUi(self, Dialog2):
        Dialog2.setObjectName("Dialog2")
        Dialog2.resize(414, 220)
        Dialog2.setMinimumSize(QtCore.QSize(414, 220))
        Dialog2.setMaximumSize(QtCore.QSize(414, 220))
        Dialog2.setStyleSheet("* {margin:0; padding:0; border: 0}\n"
"\n"
"QDialog{background-color:#efefef}\n"
"\n"
"QPushButton{\n"
"    background-color: #ffdf00;\n"
"    border: 0;\n"
"border-radius:25; padding:0; margin:0\n"
"}\n"
"QPushButton::disabled{background-color:#cbcbcb}\n"
"QPushButton:hover{ background-color: #f1d100}\n"
"QPushButton:pressed{background-color:#dfc200 }\n"
"\n"
"QLineEdit{\n"
"background-color: transparent;\n"
"border: 2px solid #b0b0b0;\n"
"padding: 5 15;\n"
"border-radius: 18\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.description_text = QtWidgets.QLabel(Dialog2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.description_text.sizePolicy().hasHeightForWidth())
        self.description_text.setSizePolicy(sizePolicy)
        self.description_text.setMinimumSize(QtCore.QSize(0, 25))
        self.description_text.setMaximumSize(QtCore.QSize(16777215, 75))
        font = QtGui.QFont()
        font.setFamily("Equinox Bold")
        font.setPointSize(14)
        self.description_text.setFont(font)
        self.description_text.setAlignment(QtCore.Qt.AlignCenter)
        self.description_text.setWordWrap(True)
        self.description_text.setObjectName("description_text")
        self.verticalLayout.addWidget(self.description_text)
        self.frame = QtWidgets.QFrame(Dialog2)
        self.frame.setMinimumSize(QtCore.QSize(0, 46))
        self.frame.setMaximumSize(QtCore.QSize(10000, 46))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.new_value = QtWidgets.QLineEdit(self.frame)
        self.new_value.setMinimumSize(QtCore.QSize(320, 45))
        self.new_value.setMaximumSize(QtCore.QSize(320, 45))
        font = QtGui.QFont()
        font.setFamily("Equinox Bold")
        font.setPointSize(14)
        self.new_value.setFont(font)
        self.new_value.setText("")
        self.new_value.setObjectName("new_value")
        self.horizontalLayout.addWidget(self.new_value)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(Dialog2)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 52))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 52))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_alt_val = QtWidgets.QPushButton(self.frame_2)
        self.btn_alt_val.setMinimumSize(QtCore.QSize(320, 50))
        self.btn_alt_val.setMaximumSize(QtCore.QSize(320, 50))
        font = QtGui.QFont()
        font.setFamily("Equinox Bold")
        font.setPointSize(14)
        self.btn_alt_val.setFont(font)
        self.btn_alt_val.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_alt_val.setStyleSheet("")
        self.btn_alt_val.setAutoDefault(False)
        self.btn_alt_val.setDefault(True)
        self.btn_alt_val.setObjectName("btn_alt_val")
        self.horizontalLayout_2.addWidget(self.btn_alt_val)
        self.verticalLayout.addWidget(self.frame_2)

        self.retranslateUi(Dialog2)
        QtCore.QMetaObject.connectSlotsByName(Dialog2)

    def retranslateUi(self, Dialog2):
        _translate = QtCore.QCoreApplication.translate
        Dialog2.setWindowTitle(_translate("Dialog2", "Alterar valor"))
        self.description_text.setText(_translate("Dialog2", "Alterar valor da Distância entre Pontos (XYZ):"))
        self.btn_alt_val.setText(_translate("Dialog2", "Alterar Valor"))
