# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\pyqt\ui\ports_barCode_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(414, 250)
        Dialog.setMinimumSize(QtCore.QSize(414, 250))
        Dialog.setMaximumSize(QtCore.QSize(414, 250))
        Dialog.setStyleSheet("* {margin:0; padding:0; border: 0}\n"
"\n"
"QDialog{background-color:#efefef}\n"
"\n"
"QPushButton{\n"
"    background-color: #ffdf00;\n"
"    border: 0;\n"
"border-radius:25; padding:0; margin:0\n"
"}\n"
"QPushButton::disabled{background-color:#cbcbcb}\n"
"QPushButton:hover{ background-color: #f1d100}\n"
"QPushButton:pressed{background-color:#dfc200 }\n"
"\n"
"QPushButton:focus {border: 0; outline:1px solid #ababab}\n"
"\n"
"QLineEdit{\n"
"background-color: transparent;\n"
"border: 2px solid #b0b0b0;\n"
"padding: 5 15;\n"
"border-radius: 18\n"
"}\n"
"\n"
"QComboBox {\n"
"    border: 1px solid #a9a9a9;\n"
"    border-radius: 25;\n"
"    padding: 0 20 0 15;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 40;\n"
"\n"
"    border:0; background-color: #ffdf00;\n"
"    border-top-right-radius: 24;\n"
"    border-bottom-right-radius: 24;\n"
"    border-left: 1px solid #a9a9a9\n"
"}\n"
"\n"
"QComboBox::down-arrow{\n"
"    image: url(:/newPrefix/assets/icons/icons/2x/outline_arrow_drop_down_black_48dp.png);\n"
"    width: 30;\n"
"    height:30;\n"
"}\n"
"\n"
"QComboBox::down-arrow:on{\n"
"    image: url(:/newPrefix/assets/icons/icons/2x/outline_arrow_drop_up_black_48dp.png);\n"
"    width: 30;\n"
"    height:30;\n"
"}\n"
"\n"
"QComboBox::drop-down:hover{\n"
"    background-color: #f1d100;\n"
"}\n"
"QComboBox::drop-down:pressed{\n"
"    background-color: #dfc200;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setContentsMargins(-1, -1, -1, 15)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setMinimumSize(QtCore.QSize(0, 75))
        self.label.setMaximumSize(QtCore.QSize(16777215, 75))
        font = QtGui.QFont()
        font.setFamily("Equinox Bold")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 15)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.comboBox = QtWidgets.QComboBox(self.frame)
        self.comboBox.setMinimumSize(QtCore.QSize(175, 50))
        self.comboBox.setMaximumSize(QtCore.QSize(175, 50))
        font = QtGui.QFont()
        font.setFamily("Equinox Bold")
        font.setPointSize(14)
        self.comboBox.setFont(font)
        self.comboBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.comboBox.setMaxVisibleItems(5)
        self.comboBox.setMaxCount(300)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout_2.addWidget(self.comboBox)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(Dialog)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 52))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 52))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setContentsMargins(15, 0, 15, 0)
        self.horizontalLayout.setSpacing(15)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_confirm = QtWidgets.QPushButton(self.frame_2)
        self.btn_confirm.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_confirm.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Equinox Bold")
        font.setPointSize(14)
        self.btn_confirm.setFont(font)
        self.btn_confirm.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/assets/icons/icons/2x/sharp_check_black_48dp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_confirm.setIcon(icon)
        self.btn_confirm.setIconSize(QtCore.QSize(25, 25))
        self.btn_confirm.setAutoDefault(False)
        self.btn_confirm.setDefault(True)
        self.btn_confirm.setObjectName("btn_confirm")
        self.horizontalLayout.addWidget(self.btn_confirm)
        self.btn_cancel = QtWidgets.QPushButton(self.frame_2)
        self.btn_cancel.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_cancel.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Equinox Bold")
        font.setPointSize(14)
        self.btn_cancel.setFont(font)
        self.btn_cancel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_cancel.setFocusPolicy(QtCore.Qt.TabFocus)
        self.btn_cancel.setStyleSheet("* {\n"
"background-color: #eece00\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: #ddbd00\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: #ccac00\n"
"}\n"
"QPushButton::disabled{background-color:#cbcbcb}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/assets/icons/icons/2x/sharp_close_black_48dp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_cancel.setIcon(icon1)
        self.btn_cancel.setIconSize(QtCore.QSize(25, 25))
        self.btn_cancel.setAutoDefault(False)
        self.btn_cancel.setObjectName("btn_cancel")
        self.horizontalLayout.addWidget(self.btn_cancel)
        self.verticalLayout.addWidget(self.frame_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Selecione a porta onde está o leitor de código de barras!"))
        self.btn_confirm.setText(_translate("Dialog", "Confirmar"))
        self.btn_cancel.setText(_translate("Dialog", "Cancelar"))
import icons_rc
