# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/login_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginDialog(object):
    def setupUi(self, LoginDialog):
        LoginDialog.setObjectName("LoginDialog")
        LoginDialog.resize(414, 236)
        LoginDialog.setMinimumSize(QtCore.QSize(414, 236))
        LoginDialog.setMaximumSize(QtCore.QSize(414, 236))
        LoginDialog.setStyleSheet("* {margin:0; padding:0; border: 0}\n"
"\n"
"QDialog{background-color:#efefef}\n"
"\n"
"QPushButton{\n"
"    background-color: #ffdf00;\n"
"    border: 0;\n"
"border-radius:25; padding:0; margin:0\n"
"}\n"
"QPushButton::disabled{background-color:#cbcbcb}\n"
"QPushButton:hover{ background-color: #f1d100}\n"
"QPushButton:pressed{background-color:#dfc200 }\n"
"\n"
"QLineEdit{\n"
"background-color: transparent;\n"
"border: 2px solid #b0b0b0;\n"
"padding: 5 15;\n"
"border-radius: 18\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(LoginDialog)
        self.verticalLayout.setContentsMargins(25, 10, 25, 10)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.description_text = QtWidgets.QLabel(LoginDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.description_text.sizePolicy().hasHeightForWidth())
        self.description_text.setSizePolicy(sizePolicy)
        self.description_text.setMinimumSize(QtCore.QSize(0, 25))
        self.description_text.setMaximumSize(QtCore.QSize(16777215, 75))
        font = QtGui.QFont()
        font.setFamily("Equinox Bold")
        font.setPointSize(14)
        self.description_text.setFont(font)
        self.description_text.setAlignment(QtCore.Qt.AlignCenter)
        self.description_text.setWordWrap(True)
        self.description_text.setObjectName("description_text")
        self.verticalLayout.addWidget(self.description_text)
        self.frame_4 = QtWidgets.QFrame(LoginDialog)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 15)
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.frame_4)
        self.frame.setMinimumSize(QtCore.QSize(0, 46))
        self.frame.setMaximumSize(QtCore.QSize(10000, 46))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.user_login = QtWidgets.QLineEdit(self.frame)
        self.user_login.setMinimumSize(QtCore.QSize(320, 45))
        self.user_login.setMaximumSize(QtCore.QSize(320, 45))
        font = QtGui.QFont()
        font.setFamily("Equinox Bold")
        font.setPointSize(14)
        self.user_login.setFont(font)
        self.user_login.setToolTip("")
        self.user_login.setInputMask("")
        self.user_login.setText("")
        self.user_login.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.user_login.setObjectName("user_login")
        self.horizontalLayout.addWidget(self.user_login)
        self.verticalLayout_2.addWidget(self.frame)
        self.frame_3 = QtWidgets.QFrame(self.frame_4)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 46))
        self.frame_3.setMaximumSize(QtCore.QSize(10000, 46))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.user_password = QtWidgets.QLineEdit(self.frame_3)
        self.user_password.setMinimumSize(QtCore.QSize(320, 45))
        self.user_password.setMaximumSize(QtCore.QSize(320, 45))
        font = QtGui.QFont()
        font.setFamily("Equinox Bold")
        font.setPointSize(14)
        self.user_password.setFont(font)
        self.user_password.setToolTip("")
        self.user_password.setInputMask("")
        self.user_password.setText("")
        self.user_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.user_password.setObjectName("user_password")
        self.horizontalLayout_3.addWidget(self.user_password)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.verticalLayout.addWidget(self.frame_4)
        self.frame_2 = QtWidgets.QFrame(LoginDialog)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 52))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 52))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_login = QtWidgets.QPushButton(self.frame_2)
        self.btn_login.setMinimumSize(QtCore.QSize(320, 50))
        self.btn_login.setMaximumSize(QtCore.QSize(320, 50))
        font = QtGui.QFont()
        font.setFamily("Equinox Bold")
        font.setPointSize(14)
        self.btn_login.setFont(font)
        self.btn_login.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_login.setStyleSheet("")
        self.btn_login.setAutoDefault(False)
        self.btn_login.setDefault(True)
        self.btn_login.setObjectName("btn_login")
        self.horizontalLayout_2.addWidget(self.btn_login)
        self.verticalLayout.addWidget(self.frame_2)

        self.retranslateUi(LoginDialog)
        QtCore.QMetaObject.connectSlotsByName(LoginDialog)

    def retranslateUi(self, LoginDialog):
        _translate = QtCore.QCoreApplication.translate
        LoginDialog.setWindowTitle(_translate("LoginDialog", "Log-In"))
        self.description_text.setText(_translate("LoginDialog", "Insira os dados de usuário abaixo:"))
        self.user_login.setPlaceholderText(_translate("LoginDialog", "Usuário"))
        self.user_password.setPlaceholderText(_translate("LoginDialog", "Senha"))
        self.btn_login.setText(_translate("LoginDialog", "Entrar"))
